/* soapClient.cpp
   Generated by gSOAP 2.8.16 from soapshop.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif

#include "StdAfx.h"
// #include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.16 2013-12-05 08:24:40 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemByCode(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemByCode *ns1__GetItemByCode, _ns1__GetItemByCodeResponse *ns1__GetItemByCodeResponse)
{	struct __ns1__GetItemByCode soap_tmp___ns1__GetItemByCode;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetItemByCode";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetItemByCode.ns1__GetItemByCode = ns1__GetItemByCode;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetItemByCode(soap, &soap_tmp___ns1__GetItemByCode);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetItemByCode(soap, &soap_tmp___ns1__GetItemByCode, "-ns1:GetItemByCode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetItemByCode(soap, &soap_tmp___ns1__GetItemByCode, "-ns1:GetItemByCode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetItemByCodeResponse)
		return soap_closesock(soap);
	ns1__GetItemByCodeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetItemByCodeResponse->soap_get(soap, "ns1:GetItemByCodeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemByItemID(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemByItemID *ns1__GetItemByItemID, _ns1__GetItemByItemIDResponse *ns1__GetItemByItemIDResponse)
{	struct __ns1__GetItemByItemID soap_tmp___ns1__GetItemByItemID;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetItemByItemID";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetItemByItemID.ns1__GetItemByItemID = ns1__GetItemByItemID;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetItemByItemID(soap, &soap_tmp___ns1__GetItemByItemID);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetItemByItemID(soap, &soap_tmp___ns1__GetItemByItemID, "-ns1:GetItemByItemID", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetItemByItemID(soap, &soap_tmp___ns1__GetItemByItemID, "-ns1:GetItemByItemID", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetItemByItemIDResponse)
		return soap_closesock(soap);
	ns1__GetItemByItemIDResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetItemByItemIDResponse->soap_get(soap, "ns1:GetItemByItemIDResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemValue(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemValue *ns1__GetItemValue, _ns1__GetItemValueResponse *ns1__GetItemValueResponse)
{	struct __ns1__GetItemValue soap_tmp___ns1__GetItemValue;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetItemValue";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetItemValue.ns1__GetItemValue = ns1__GetItemValue;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetItemValue(soap, &soap_tmp___ns1__GetItemValue);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetItemValue(soap, &soap_tmp___ns1__GetItemValue, "-ns1:GetItemValue", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetItemValue(soap, &soap_tmp___ns1__GetItemValue, "-ns1:GetItemValue", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetItemValueResponse)
		return soap_closesock(soap);
	ns1__GetItemValueResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetItemValueResponse->soap_get(soap, "ns1:GetItemValueResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetClothingID(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetClothingID *ns1__GetClothingID, _ns1__GetClothingIDResponse *ns1__GetClothingIDResponse)
{	struct __ns1__GetClothingID soap_tmp___ns1__GetClothingID;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetClothingID";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetClothingID.ns1__GetClothingID = ns1__GetClothingID;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetClothingID(soap, &soap_tmp___ns1__GetClothingID);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetClothingID(soap, &soap_tmp___ns1__GetClothingID, "-ns1:GetClothingID", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetClothingID(soap, &soap_tmp___ns1__GetClothingID, "-ns1:GetClothingID", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetClothingIDResponse)
		return soap_closesock(soap);
	ns1__GetClothingIDResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetClothingIDResponse->soap_get(soap, "ns1:GetClothingIDResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__AwardItem(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__AwardItem *ns1__AwardItem, _ns1__AwardItemResponse *ns1__AwardItemResponse)
{	struct __ns1__AwardItem soap_tmp___ns1__AwardItem;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AwardItem";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__AwardItem.ns1__AwardItem = ns1__AwardItem;
	soap_serializeheader(soap);
	soap_serialize___ns1__AwardItem(soap, &soap_tmp___ns1__AwardItem);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__AwardItem(soap, &soap_tmp___ns1__AwardItem, "-ns1:AwardItem", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__AwardItem(soap, &soap_tmp___ns1__AwardItem, "-ns1:AwardItem", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__AwardItemResponse)
		return soap_closesock(soap);
	ns1__AwardItemResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__AwardItemResponse->soap_get(soap, "ns1:AwardItemResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAwardItem(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAwardItem *ns1__GetAwardItem, _ns1__GetAwardItemResponse *ns1__GetAwardItemResponse)
{	struct __ns1__GetAwardItem soap_tmp___ns1__GetAwardItem;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetAwardItem";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAwardItem.ns1__GetAwardItem = ns1__GetAwardItem;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAwardItem(soap, &soap_tmp___ns1__GetAwardItem);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAwardItem(soap, &soap_tmp___ns1__GetAwardItem, "-ns1:GetAwardItem", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAwardItem(soap, &soap_tmp___ns1__GetAwardItem, "-ns1:GetAwardItem", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetAwardItemResponse)
		return soap_closesock(soap);
	ns1__GetAwardItemResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAwardItemResponse->soap_get(soap, "ns1:GetAwardItemResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAwardInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAwardInfo *ns1__GetAwardInfo, _ns1__GetAwardInfoResponse *ns1__GetAwardInfoResponse)
{	struct __ns1__GetAwardInfo soap_tmp___ns1__GetAwardInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetAwardInfo";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAwardInfo.ns1__GetAwardInfo = ns1__GetAwardInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAwardInfo(soap, &soap_tmp___ns1__GetAwardInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAwardInfo(soap, &soap_tmp___ns1__GetAwardInfo, "-ns1:GetAwardInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAwardInfo(soap, &soap_tmp___ns1__GetAwardInfo, "-ns1:GetAwardInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetAwardInfoResponse)
		return soap_closesock(soap);
	ns1__GetAwardInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAwardInfoResponse->soap_get(soap, "ns1:GetAwardInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Lottery(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__Lottery *ns1__Lottery, _ns1__LotteryResponse *ns1__LotteryResponse)
{	struct __ns1__Lottery soap_tmp___ns1__Lottery;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Lottery";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Lottery.ns1__Lottery = ns1__Lottery;
	soap_serializeheader(soap);
	soap_serialize___ns1__Lottery(soap, &soap_tmp___ns1__Lottery);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Lottery(soap, &soap_tmp___ns1__Lottery, "-ns1:Lottery", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Lottery(soap, &soap_tmp___ns1__Lottery, "-ns1:Lottery", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__LotteryResponse)
		return soap_closesock(soap);
	ns1__LotteryResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__LotteryResponse->soap_get(soap, "ns1:LotteryResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryPrize(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryPrize *ns1__GetLotteryPrize, _ns1__GetLotteryPrizeResponse *ns1__GetLotteryPrizeResponse)
{	struct __ns1__GetLotteryPrize soap_tmp___ns1__GetLotteryPrize;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetLotteryPrize";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetLotteryPrize.ns1__GetLotteryPrize = ns1__GetLotteryPrize;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetLotteryPrize(soap, &soap_tmp___ns1__GetLotteryPrize);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetLotteryPrize(soap, &soap_tmp___ns1__GetLotteryPrize, "-ns1:GetLotteryPrize", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetLotteryPrize(soap, &soap_tmp___ns1__GetLotteryPrize, "-ns1:GetLotteryPrize", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetLotteryPrizeResponse)
		return soap_closesock(soap);
	ns1__GetLotteryPrizeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetLotteryPrizeResponse->soap_get(soap, "ns1:GetLotteryPrizeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryWinningTop(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryWinningTop *ns1__GetLotteryWinningTop, _ns1__GetLotteryWinningTopResponse *ns1__GetLotteryWinningTopResponse)
{	struct __ns1__GetLotteryWinningTop soap_tmp___ns1__GetLotteryWinningTop;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetLotteryWinningTop";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetLotteryWinningTop.ns1__GetLotteryWinningTop = ns1__GetLotteryWinningTop;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetLotteryWinningTop(soap, &soap_tmp___ns1__GetLotteryWinningTop);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetLotteryWinningTop(soap, &soap_tmp___ns1__GetLotteryWinningTop, "-ns1:GetLotteryWinningTop", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetLotteryWinningTop(soap, &soap_tmp___ns1__GetLotteryWinningTop, "-ns1:GetLotteryWinningTop", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetLotteryWinningTopResponse)
		return soap_closesock(soap);
	ns1__GetLotteryWinningTopResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetLotteryWinningTopResponse->soap_get(soap, "ns1:GetLotteryWinningTopResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryWinningList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryWinningList *ns1__GetLotteryWinningList, _ns1__GetLotteryWinningListResponse *ns1__GetLotteryWinningListResponse)
{	struct __ns1__GetLotteryWinningList soap_tmp___ns1__GetLotteryWinningList;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetLotteryWinningList";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetLotteryWinningList.ns1__GetLotteryWinningList = ns1__GetLotteryWinningList;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetLotteryWinningList(soap, &soap_tmp___ns1__GetLotteryWinningList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetLotteryWinningList(soap, &soap_tmp___ns1__GetLotteryWinningList, "-ns1:GetLotteryWinningList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetLotteryWinningList(soap, &soap_tmp___ns1__GetLotteryWinningList, "-ns1:GetLotteryWinningList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetLotteryWinningListResponse)
		return soap_closesock(soap);
	ns1__GetLotteryWinningListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetLotteryWinningListResponse->soap_get(soap, "ns1:GetLotteryWinningListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemByCode_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemByCode *ns1__GetItemByCode, _ns1__GetItemByCodeResponse *ns1__GetItemByCodeResponse)
{	struct __ns1__GetItemByCode_ soap_tmp___ns1__GetItemByCode_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetItemByCode";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetItemByCode_.ns1__GetItemByCode = ns1__GetItemByCode;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetItemByCode_(soap, &soap_tmp___ns1__GetItemByCode_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetItemByCode_(soap, &soap_tmp___ns1__GetItemByCode_, "-ns1:GetItemByCode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetItemByCode_(soap, &soap_tmp___ns1__GetItemByCode_, "-ns1:GetItemByCode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetItemByCodeResponse)
		return soap_closesock(soap);
	ns1__GetItemByCodeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetItemByCodeResponse->soap_get(soap, "ns1:GetItemByCodeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemByItemID_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemByItemID *ns1__GetItemByItemID, _ns1__GetItemByItemIDResponse *ns1__GetItemByItemIDResponse)
{	struct __ns1__GetItemByItemID_ soap_tmp___ns1__GetItemByItemID_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetItemByItemID";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetItemByItemID_.ns1__GetItemByItemID = ns1__GetItemByItemID;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetItemByItemID_(soap, &soap_tmp___ns1__GetItemByItemID_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetItemByItemID_(soap, &soap_tmp___ns1__GetItemByItemID_, "-ns1:GetItemByItemID", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetItemByItemID_(soap, &soap_tmp___ns1__GetItemByItemID_, "-ns1:GetItemByItemID", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetItemByItemIDResponse)
		return soap_closesock(soap);
	ns1__GetItemByItemIDResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetItemByItemIDResponse->soap_get(soap, "ns1:GetItemByItemIDResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemValue_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemValue *ns1__GetItemValue, _ns1__GetItemValueResponse *ns1__GetItemValueResponse)
{	struct __ns1__GetItemValue_ soap_tmp___ns1__GetItemValue_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetItemValue";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetItemValue_.ns1__GetItemValue = ns1__GetItemValue;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetItemValue_(soap, &soap_tmp___ns1__GetItemValue_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetItemValue_(soap, &soap_tmp___ns1__GetItemValue_, "-ns1:GetItemValue", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetItemValue_(soap, &soap_tmp___ns1__GetItemValue_, "-ns1:GetItemValue", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetItemValueResponse)
		return soap_closesock(soap);
	ns1__GetItemValueResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetItemValueResponse->soap_get(soap, "ns1:GetItemValueResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetClothingID_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetClothingID *ns1__GetClothingID, _ns1__GetClothingIDResponse *ns1__GetClothingIDResponse)
{	struct __ns1__GetClothingID_ soap_tmp___ns1__GetClothingID_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetClothingID";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetClothingID_.ns1__GetClothingID = ns1__GetClothingID;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetClothingID_(soap, &soap_tmp___ns1__GetClothingID_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetClothingID_(soap, &soap_tmp___ns1__GetClothingID_, "-ns1:GetClothingID", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetClothingID_(soap, &soap_tmp___ns1__GetClothingID_, "-ns1:GetClothingID", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetClothingIDResponse)
		return soap_closesock(soap);
	ns1__GetClothingIDResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetClothingIDResponse->soap_get(soap, "ns1:GetClothingIDResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__AwardItem_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__AwardItem *ns1__AwardItem, _ns1__AwardItemResponse *ns1__AwardItemResponse)
{	struct __ns1__AwardItem_ soap_tmp___ns1__AwardItem_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/AwardItem";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__AwardItem_.ns1__AwardItem = ns1__AwardItem;
	soap_serializeheader(soap);
	soap_serialize___ns1__AwardItem_(soap, &soap_tmp___ns1__AwardItem_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__AwardItem_(soap, &soap_tmp___ns1__AwardItem_, "-ns1:AwardItem", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__AwardItem_(soap, &soap_tmp___ns1__AwardItem_, "-ns1:AwardItem", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__AwardItemResponse)
		return soap_closesock(soap);
	ns1__AwardItemResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__AwardItemResponse->soap_get(soap, "ns1:AwardItemResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAwardItem_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAwardItem *ns1__GetAwardItem, _ns1__GetAwardItemResponse *ns1__GetAwardItemResponse)
{	struct __ns1__GetAwardItem_ soap_tmp___ns1__GetAwardItem_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetAwardItem";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAwardItem_.ns1__GetAwardItem = ns1__GetAwardItem;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAwardItem_(soap, &soap_tmp___ns1__GetAwardItem_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAwardItem_(soap, &soap_tmp___ns1__GetAwardItem_, "-ns1:GetAwardItem", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAwardItem_(soap, &soap_tmp___ns1__GetAwardItem_, "-ns1:GetAwardItem", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetAwardItemResponse)
		return soap_closesock(soap);
	ns1__GetAwardItemResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAwardItemResponse->soap_get(soap, "ns1:GetAwardItemResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAwardInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAwardInfo *ns1__GetAwardInfo, _ns1__GetAwardInfoResponse *ns1__GetAwardInfoResponse)
{	struct __ns1__GetAwardInfo_ soap_tmp___ns1__GetAwardInfo_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetAwardInfo";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAwardInfo_.ns1__GetAwardInfo = ns1__GetAwardInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAwardInfo_(soap, &soap_tmp___ns1__GetAwardInfo_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAwardInfo_(soap, &soap_tmp___ns1__GetAwardInfo_, "-ns1:GetAwardInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAwardInfo_(soap, &soap_tmp___ns1__GetAwardInfo_, "-ns1:GetAwardInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetAwardInfoResponse)
		return soap_closesock(soap);
	ns1__GetAwardInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetAwardInfoResponse->soap_get(soap, "ns1:GetAwardInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Lottery_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__Lottery *ns1__Lottery, _ns1__LotteryResponse *ns1__LotteryResponse)
{	struct __ns1__Lottery_ soap_tmp___ns1__Lottery_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/Lottery";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Lottery_.ns1__Lottery = ns1__Lottery;
	soap_serializeheader(soap);
	soap_serialize___ns1__Lottery_(soap, &soap_tmp___ns1__Lottery_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Lottery_(soap, &soap_tmp___ns1__Lottery_, "-ns1:Lottery", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Lottery_(soap, &soap_tmp___ns1__Lottery_, "-ns1:Lottery", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__LotteryResponse)
		return soap_closesock(soap);
	ns1__LotteryResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__LotteryResponse->soap_get(soap, "ns1:LotteryResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryPrize_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryPrize *ns1__GetLotteryPrize, _ns1__GetLotteryPrizeResponse *ns1__GetLotteryPrizeResponse)
{	struct __ns1__GetLotteryPrize_ soap_tmp___ns1__GetLotteryPrize_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetLotteryPrize";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetLotteryPrize_.ns1__GetLotteryPrize = ns1__GetLotteryPrize;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetLotteryPrize_(soap, &soap_tmp___ns1__GetLotteryPrize_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetLotteryPrize_(soap, &soap_tmp___ns1__GetLotteryPrize_, "-ns1:GetLotteryPrize", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetLotteryPrize_(soap, &soap_tmp___ns1__GetLotteryPrize_, "-ns1:GetLotteryPrize", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetLotteryPrizeResponse)
		return soap_closesock(soap);
	ns1__GetLotteryPrizeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetLotteryPrizeResponse->soap_get(soap, "ns1:GetLotteryPrizeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryWinningTop_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryWinningTop *ns1__GetLotteryWinningTop, _ns1__GetLotteryWinningTopResponse *ns1__GetLotteryWinningTopResponse)
{	struct __ns1__GetLotteryWinningTop_ soap_tmp___ns1__GetLotteryWinningTop_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetLotteryWinningTop";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetLotteryWinningTop_.ns1__GetLotteryWinningTop = ns1__GetLotteryWinningTop;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetLotteryWinningTop_(soap, &soap_tmp___ns1__GetLotteryWinningTop_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetLotteryWinningTop_(soap, &soap_tmp___ns1__GetLotteryWinningTop_, "-ns1:GetLotteryWinningTop", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetLotteryWinningTop_(soap, &soap_tmp___ns1__GetLotteryWinningTop_, "-ns1:GetLotteryWinningTop", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetLotteryWinningTopResponse)
		return soap_closesock(soap);
	ns1__GetLotteryWinningTopResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetLotteryWinningTopResponse->soap_get(soap, "ns1:GetLotteryWinningTopResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryWinningList_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryWinningList *ns1__GetLotteryWinningList, _ns1__GetLotteryWinningListResponse *ns1__GetLotteryWinningListResponse)
{	struct __ns1__GetLotteryWinningList_ soap_tmp___ns1__GetLotteryWinningList_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://mallsvc.uc108.org:3093/ItemAwardService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/GetLotteryWinningList";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetLotteryWinningList_.ns1__GetLotteryWinningList = ns1__GetLotteryWinningList;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetLotteryWinningList_(soap, &soap_tmp___ns1__GetLotteryWinningList_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetLotteryWinningList_(soap, &soap_tmp___ns1__GetLotteryWinningList_, "-ns1:GetLotteryWinningList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetLotteryWinningList_(soap, &soap_tmp___ns1__GetLotteryWinningList_, "-ns1:GetLotteryWinningList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetLotteryWinningListResponse)
		return soap_closesock(soap);
	ns1__GetLotteryWinningListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetLotteryWinningListResponse->soap_get(soap, "ns1:GetLotteryWinningListResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
