/* soapStub.h
   Generated by gSOAP 2.8.16 from soapshop.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20816
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_ns1__KindEnum
#define SOAP_TYPE_ns1__KindEnum (36)
/* Bitmask ns1:KindEnum */
enum ns1__KindEnum { ns1__KindEnum__Goods = 1, ns1__KindEnum__NotForSale = 2, ns1__KindEnum__Gift = 4, ns1__KindEnum__Complex = 8 };
#endif

#ifndef SOAP_TYPE_ns1__ItemTypeEnum
#define SOAP_TYPE_ns1__ItemTypeEnum (37)
/* Bitmask ns1:ItemTypeEnum */
enum ns1__ItemTypeEnum { ns1__ItemTypeEnum__Props = 1, ns1__ItemTypeEnum__Clothes = 2 };
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__ItemInfo
#define SOAP_TYPE_ns1__ItemInfo (8)
/* ns1:ItemInfo */
class SOAP_CMAC ns1__ItemInfo
{
public:
	int ItemID;	/* required element of type xsd:int */
	int KindID;	/* required element of type xsd:int */
	enum ns1__KindEnum KindEnumValue;	/* required element of type ns1:KindEnum */
	int ItemTypeID;	/* required element of type xsd:int */
	char *ClassID;	/* optional element of type xsd:string */
	enum ns1__ItemTypeEnum ItemTypeEnumValue;	/* required element of type ns1:ItemTypeEnum */
	int PlatformID;	/* required element of type xsd:int */
	char *ItemName;	/* optional element of type xsd:string */
	char *ItemCode;	/* optional element of type xsd:string */
	char *Remark;	/* optional element of type xsd:string */
	char *Intro;	/* optional element of type xsd:string */
	char *Image;	/* optional element of type xsd:string */
	int RarityValue;	/* required element of type xsd:int */
	int ExpiryDays;	/* required element of type xsd:int */
	time_t ExpiryTime;	/* required element of type xsd:dateTime */
	bool IsDuration;	/* required element of type xsd:boolean */
	bool IsAllowRenewal;	/* required element of type xsd:boolean */
	bool IsUseInMall;	/* required element of type xsd:boolean */
	bool IsAllowPawn;	/* required element of type xsd:boolean */
	bool IsAllowDoff;	/* required element of type xsd:boolean */
	bool IsMemberUse;	/* required element of type xsd:boolean */
	bool IsOnlyGiveMember;	/* required element of type xsd:boolean */
	int GiftTimes;	/* required element of type xsd:int */
	int UseExperienceLevel;	/* required element of type xsd:int */
	char *PropertyValue;	/* optional element of type xsd:string */
	char *PropertyText;	/* optional element of type xsd:string */
	char *UseText;	/* optional element of type xsd:string */
	char *UseUrl;	/* optional element of type xsd:string */
	char *UseOpenType;	/* optional element of type xsd:string */
	char *ItemValue;	/* required element of type xsd:decimal */
	bool IsStop;	/* required element of type xsd:boolean */
	time_t LastUpdateTime;	/* required element of type xsd:dateTime */
	int AdminID;	/* required element of type xsd:int */
	int GiveLevel;	/* required element of type xsd:int */
	char *UnitID;	/* optional element of type xsd:string */
	int ItemValueUnitID;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique id SOAP_TYPE_ns1__ItemInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ItemInfo() { ns1__ItemInfo::soap_default(NULL); }
	virtual ~ns1__ItemInfo() { }
};
#endif

#ifndef SOAP_TYPE_ns1__ArrayOfAwardItemInfo
#define SOAP_TYPE_ns1__ArrayOfAwardItemInfo (9)
/* ns1:ArrayOfAwardItemInfo */
class SOAP_CMAC ns1__ArrayOfAwardItemInfo
{
public:
	int __sizeAwardItemInfo;	/* sequence of elements <AwardItemInfo> */
	class ns1__AwardItemInfo **AwardItemInfo;	/* optional element of type ns1:AwardItemInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique id SOAP_TYPE_ns1__ArrayOfAwardItemInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ArrayOfAwardItemInfo() { ns1__ArrayOfAwardItemInfo::soap_default(NULL); }
	virtual ~ns1__ArrayOfAwardItemInfo() { }
};
#endif

#ifndef SOAP_TYPE_ns1__AwardItemInfo
#define SOAP_TYPE_ns1__AwardItemInfo (10)
/* ns1:AwardItemInfo */
class SOAP_CMAC ns1__AwardItemInfo
{
public:
	int ID;	/* required element of type xsd:int */
	int AwardID;	/* required element of type xsd:int */
	int ItemID;	/* required element of type xsd:int */
	int UnitID;	/* required element of type xsd:int */
	int TotalNumber;	/* required element of type xsd:int */
	int EachNumber;	/* required element of type xsd:int */
	int AwardedNumber;	/* required element of type xsd:int */
	time_t ExpiryTime;	/* required element of type xsd:dateTime */
	int ExpiryDays;	/* required element of type xsd:int */
	int GiftTimes;	/* required element of type xsd:int */
	char *ItemName;	/* optional element of type xsd:string */
	char *ItemCode;	/* optional element of type xsd:string */
	char *UnitName;	/* optional element of type xsd:string */
	char *ItemImage;	/* optional element of type xsd:string */
	char *AwardedItemValue;	/* required element of type xsd:decimal */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique id SOAP_TYPE_ns1__AwardItemInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__AwardItemInfo() { ns1__AwardItemInfo::soap_default(NULL); }
	virtual ~ns1__AwardItemInfo() { }
};
#endif

#ifndef SOAP_TYPE_ns1__AwardInfo
#define SOAP_TYPE_ns1__AwardInfo (11)
/* ns1:AwardInfo */
class SOAP_CMAC ns1__AwardInfo
{
public:
	int AwardID;	/* required element of type xsd:int */
	char *AwardGuid;	/* optional element of type xsd:string */
	char *Title;	/* optional element of type xsd:string */
	int AwardType;	/* required element of type xsd:int */
	int TotalNumber;	/* required element of type xsd:int */
	int AwardedNumber;	/* required element of type xsd:int */
	time_t BeginTime;	/* required element of type xsd:dateTime */
	time_t EndTime;	/* required element of type xsd:dateTime */
	char *AppsCode;	/* optional element of type xsd:string */
	char *Remark;	/* optional element of type xsd:string */
	char *TotalItemValue;	/* required element of type xsd:decimal */
	int StatusID;	/* required element of type xsd:int */
	int AdminID;	/* required element of type xsd:int */
	time_t Created;	/* required element of type xsd:dateTime */
	bool IsAwardAgain;	/* required element of type xsd:boolean */
	bool IsLottery;	/* required element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique id SOAP_TYPE_ns1__AwardInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__AwardInfo() { ns1__AwardInfo::soap_default(NULL); }
	virtual ~ns1__AwardInfo() { }
};
#endif

#ifndef SOAP_TYPE_ns1__AwardLotteryPrizeInfo
#define SOAP_TYPE_ns1__AwardLotteryPrizeInfo (12)
/* ns1:AwardLotteryPrizeInfo */
class SOAP_CMAC ns1__AwardLotteryPrizeInfo
{
public:
	int PrizeID;	/* required element of type xsd:int */
	int AwardID;	/* required element of type xsd:int */
	char *PrizeName;	/* optional element of type xsd:string */
	char *PrizeItemCode;	/* optional element of type xsd:string */
	int PrizeIndex;	/* required element of type xsd:int */
	char *WinningRate;	/* required element of type xsd:decimal */
	char *PrizeValue;	/* required element of type xsd:decimal */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 12; } /* = unique id SOAP_TYPE_ns1__AwardLotteryPrizeInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__AwardLotteryPrizeInfo() { ns1__AwardLotteryPrizeInfo::soap_default(NULL); }
	virtual ~ns1__AwardLotteryPrizeInfo() { }
};
#endif

#ifndef SOAP_TYPE_ns1__ArrayOfAwardLotteryPrizeInfo
#define SOAP_TYPE_ns1__ArrayOfAwardLotteryPrizeInfo (13)
/* ns1:ArrayOfAwardLotteryPrizeInfo */
class SOAP_CMAC ns1__ArrayOfAwardLotteryPrizeInfo
{
public:
	int __sizeAwardLotteryPrizeInfo;	/* sequence of elements <AwardLotteryPrizeInfo> */
	ns1__AwardLotteryPrizeInfo **AwardLotteryPrizeInfo;	/* optional element of type ns1:AwardLotteryPrizeInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 13; } /* = unique id SOAP_TYPE_ns1__ArrayOfAwardLotteryPrizeInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         ns1__ArrayOfAwardLotteryPrizeInfo() { ns1__ArrayOfAwardLotteryPrizeInfo::soap_default(NULL); }
	virtual ~ns1__ArrayOfAwardLotteryPrizeInfo() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetItemByCode
#define SOAP_TYPE__ns1__GetItemByCode (14)
/* ns1:GetItemByCode */
class SOAP_CMAC _ns1__GetItemByCode
{
public:
	char *itemCode;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 14; } /* = unique id SOAP_TYPE__ns1__GetItemByCode */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetItemByCode() { _ns1__GetItemByCode::soap_default(NULL); }
	virtual ~_ns1__GetItemByCode() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetItemByCodeResponse
#define SOAP_TYPE__ns1__GetItemByCodeResponse (15)
/* ns1:GetItemByCodeResponse */
class SOAP_CMAC _ns1__GetItemByCodeResponse
{
public:
	ns1__ItemInfo *GetItemByCodeResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ItemInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 15; } /* = unique id SOAP_TYPE__ns1__GetItemByCodeResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetItemByCodeResponse() { _ns1__GetItemByCodeResponse::soap_default(NULL); }
	virtual ~_ns1__GetItemByCodeResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetItemByItemID
#define SOAP_TYPE__ns1__GetItemByItemID (16)
/* ns1:GetItemByItemID */
class SOAP_CMAC _ns1__GetItemByItemID
{
public:
	int itemID;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 16; } /* = unique id SOAP_TYPE__ns1__GetItemByItemID */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetItemByItemID() { _ns1__GetItemByItemID::soap_default(NULL); }
	virtual ~_ns1__GetItemByItemID() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetItemByItemIDResponse
#define SOAP_TYPE__ns1__GetItemByItemIDResponse (17)
/* ns1:GetItemByItemIDResponse */
class SOAP_CMAC _ns1__GetItemByItemIDResponse
{
public:
	ns1__ItemInfo *GetItemByItemIDResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ItemInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 17; } /* = unique id SOAP_TYPE__ns1__GetItemByItemIDResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetItemByItemIDResponse() { _ns1__GetItemByItemIDResponse::soap_default(NULL); }
	virtual ~_ns1__GetItemByItemIDResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetItemValue
#define SOAP_TYPE__ns1__GetItemValue (18)
/* ns1:GetItemValue */
class SOAP_CMAC _ns1__GetItemValue
{
public:
	int itemID;	/* required element of type xsd:int */
	int unitID;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 18; } /* = unique id SOAP_TYPE__ns1__GetItemValue */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetItemValue() { _ns1__GetItemValue::soap_default(NULL); }
	virtual ~_ns1__GetItemValue() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetItemValueResponse
#define SOAP_TYPE__ns1__GetItemValueResponse (19)
/* ns1:GetItemValueResponse */
class SOAP_CMAC _ns1__GetItemValueResponse
{
public:
	char *GetItemValueResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:decimal */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 19; } /* = unique id SOAP_TYPE__ns1__GetItemValueResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetItemValueResponse() { _ns1__GetItemValueResponse::soap_default(NULL); }
	virtual ~_ns1__GetItemValueResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetClothingID
#define SOAP_TYPE__ns1__GetClothingID (20)
/* ns1:GetClothingID */
class SOAP_CMAC _ns1__GetClothingID
{
public:
	int itemID;	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 20; } /* = unique id SOAP_TYPE__ns1__GetClothingID */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetClothingID() { _ns1__GetClothingID::soap_default(NULL); }
	virtual ~_ns1__GetClothingID() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetClothingIDResponse
#define SOAP_TYPE__ns1__GetClothingIDResponse (21)
/* ns1:GetClothingIDResponse */
class SOAP_CMAC _ns1__GetClothingIDResponse
{
public:
	int GetClothingIDResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 21; } /* = unique id SOAP_TYPE__ns1__GetClothingIDResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetClothingIDResponse() { _ns1__GetClothingIDResponse::soap_default(NULL); }
	virtual ~_ns1__GetClothingIDResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__AwardItem
#define SOAP_TYPE__ns1__AwardItem (22)
/* ns1:AwardItem */
class SOAP_CMAC _ns1__AwardItem
{
public:
	char *appCode;	/* optional element of type xsd:string */
	char *accessKey;	/* optional element of type xsd:string */
	char *awardGuid;	/* optional element of type xsd:string */
	int userID;	/* required element of type xsd:int */
	char *userName;	/* optional element of type xsd:string */
	char *userIP;	/* optional element of type xsd:string */
	char *designationItem;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 22; } /* = unique id SOAP_TYPE__ns1__AwardItem */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__AwardItem() { _ns1__AwardItem::soap_default(NULL); }
	virtual ~_ns1__AwardItem() { }
};
#endif

#ifndef SOAP_TYPE__ns1__AwardItemResponse
#define SOAP_TYPE__ns1__AwardItemResponse (23)
/* ns1:AwardItemResponse */
class SOAP_CMAC _ns1__AwardItemResponse
{
public:
	bool AwardItemResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	char *msg;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 23; } /* = unique id SOAP_TYPE__ns1__AwardItemResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__AwardItemResponse() { _ns1__AwardItemResponse::soap_default(NULL); }
	virtual ~_ns1__AwardItemResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetAwardItem
#define SOAP_TYPE__ns1__GetAwardItem (24)
/* ns1:GetAwardItem */
class SOAP_CMAC _ns1__GetAwardItem
{
public:
	char *awardGuid;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 24; } /* = unique id SOAP_TYPE__ns1__GetAwardItem */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetAwardItem() { _ns1__GetAwardItem::soap_default(NULL); }
	virtual ~_ns1__GetAwardItem() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetAwardItemResponse
#define SOAP_TYPE__ns1__GetAwardItemResponse (25)
/* ns1:GetAwardItemResponse */
class SOAP_CMAC _ns1__GetAwardItemResponse
{
public:
	ns1__ArrayOfAwardItemInfo *GetAwardItemResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ArrayOfAwardItemInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 25; } /* = unique id SOAP_TYPE__ns1__GetAwardItemResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetAwardItemResponse() { _ns1__GetAwardItemResponse::soap_default(NULL); }
	virtual ~_ns1__GetAwardItemResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetAwardInfo
#define SOAP_TYPE__ns1__GetAwardInfo (26)
/* ns1:GetAwardInfo */
class SOAP_CMAC _ns1__GetAwardInfo
{
public:
	char *awardGuid;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 26; } /* = unique id SOAP_TYPE__ns1__GetAwardInfo */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetAwardInfo() { _ns1__GetAwardInfo::soap_default(NULL); }
	virtual ~_ns1__GetAwardInfo() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetAwardInfoResponse
#define SOAP_TYPE__ns1__GetAwardInfoResponse (27)
/* ns1:GetAwardInfoResponse */
class SOAP_CMAC _ns1__GetAwardInfoResponse
{
public:
	ns1__AwardInfo *GetAwardInfoResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:AwardInfo */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 27; } /* = unique id SOAP_TYPE__ns1__GetAwardInfoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetAwardInfoResponse() { _ns1__GetAwardInfoResponse::soap_default(NULL); }
	virtual ~_ns1__GetAwardInfoResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__Lottery
#define SOAP_TYPE__ns1__Lottery (28)
/* ns1:Lottery */
class SOAP_CMAC _ns1__Lottery
{
public:
	char *appCode;	/* optional element of type xsd:string */
	char *accessKey;	/* optional element of type xsd:string */
	char *awardGuid;	/* optional element of type xsd:string */
	int userID;	/* required element of type xsd:int */
	char *userName;	/* optional element of type xsd:string */
	char *userIP;	/* optional element of type xsd:string */
	char *credential;	/* optional element of type xsd:string */
	char *remark;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 28; } /* = unique id SOAP_TYPE__ns1__Lottery */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__Lottery() { _ns1__Lottery::soap_default(NULL); }
	virtual ~_ns1__Lottery() { }
};
#endif

#ifndef SOAP_TYPE__ns1__LotteryResponse
#define SOAP_TYPE__ns1__LotteryResponse (29)
/* ns1:LotteryResponse */
class SOAP_CMAC _ns1__LotteryResponse
{
public:
	bool LotteryResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	ns1__AwardLotteryPrizeInfo *prizeInfo;	/* optional element of type ns1:AwardLotteryPrizeInfo */
	char *msg;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 29; } /* = unique id SOAP_TYPE__ns1__LotteryResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__LotteryResponse() { _ns1__LotteryResponse::soap_default(NULL); }
	virtual ~_ns1__LotteryResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetLotteryPrize
#define SOAP_TYPE__ns1__GetLotteryPrize (30)
/* ns1:GetLotteryPrize */
class SOAP_CMAC _ns1__GetLotteryPrize
{
public:
	char *appCode;	/* optional element of type xsd:string */
	char *accessKey;	/* optional element of type xsd:string */
	char *awardGuid;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 30; } /* = unique id SOAP_TYPE__ns1__GetLotteryPrize */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetLotteryPrize() { _ns1__GetLotteryPrize::soap_default(NULL); }
	virtual ~_ns1__GetLotteryPrize() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetLotteryPrizeResponse
#define SOAP_TYPE__ns1__GetLotteryPrizeResponse (31)
/* ns1:GetLotteryPrizeResponse */
class SOAP_CMAC _ns1__GetLotteryPrizeResponse
{
public:
	ns1__ArrayOfAwardLotteryPrizeInfo *GetLotteryPrizeResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ArrayOfAwardLotteryPrizeInfo */
	char *msg;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 31; } /* = unique id SOAP_TYPE__ns1__GetLotteryPrizeResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetLotteryPrizeResponse() { _ns1__GetLotteryPrizeResponse::soap_default(NULL); }
	virtual ~_ns1__GetLotteryPrizeResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetLotteryWinningTop
#define SOAP_TYPE__ns1__GetLotteryWinningTop (32)
/* ns1:GetLotteryWinningTop */
class SOAP_CMAC _ns1__GetLotteryWinningTop
{
public:
	char *appCode;	/* optional element of type xsd:string */
	char *accessKey;	/* optional element of type xsd:string */
	char *awardGuid;	/* optional element of type xsd:string */
	int top;	/* required element of type xsd:int */
	char *prizeIndex;	/* optional element of type xsd:string */
	char *prizeID;	/* optional element of type xsd:string */
	char *prizeValue;	/* required element of type xsd:decimal */
	time_t dtBegin;	/* required element of type xsd:dateTime */
	time_t dtEnd;	/* required element of type xsd:dateTime */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 32; } /* = unique id SOAP_TYPE__ns1__GetLotteryWinningTop */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetLotteryWinningTop() { _ns1__GetLotteryWinningTop::soap_default(NULL); }
	virtual ~_ns1__GetLotteryWinningTop() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetLotteryWinningTopResponse_GetLotteryWinningTopResult
#define SOAP_TYPE__ns1__GetLotteryWinningTopResponse_GetLotteryWinningTopResult (49)
/* ns1:GetLotteryWinningTopResponse-GetLotteryWinningTopResult */
class SOAP_CMAC _ns1__GetLotteryWinningTopResponse_GetLotteryWinningTopResult
{
public:
	int __size;	/* sequence of elements <-any> */
	char *__any;
	char *__any_;
public:
	virtual int soap_type() const { return 49; } /* = unique id SOAP_TYPE__ns1__GetLotteryWinningTopResponse_GetLotteryWinningTopResult */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetLotteryWinningTopResponse_GetLotteryWinningTopResult() { _ns1__GetLotteryWinningTopResponse_GetLotteryWinningTopResult::soap_default(NULL); }
	virtual ~_ns1__GetLotteryWinningTopResponse_GetLotteryWinningTopResult() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetLotteryWinningTopResponse
#define SOAP_TYPE__ns1__GetLotteryWinningTopResponse (33)
/* ns1:GetLotteryWinningTopResponse */
class SOAP_CMAC _ns1__GetLotteryWinningTopResponse
{
public:
	_ns1__GetLotteryWinningTopResponse_GetLotteryWinningTopResult *GetLotteryWinningTopResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:GetLotteryWinningTopResponse-GetLotteryWinningTopResult */
	char *msg;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 33; } /* = unique id SOAP_TYPE__ns1__GetLotteryWinningTopResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetLotteryWinningTopResponse() { _ns1__GetLotteryWinningTopResponse::soap_default(NULL); }
	virtual ~_ns1__GetLotteryWinningTopResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetLotteryWinningList
#define SOAP_TYPE__ns1__GetLotteryWinningList (34)
/* ns1:GetLotteryWinningList */
class SOAP_CMAC _ns1__GetLotteryWinningList
{
public:
	char *appCode;	/* optional element of type xsd:string */
	char *accessKey;	/* optional element of type xsd:string */
	char *awardGuid;	/* optional element of type xsd:string */
	int pageIndex;	/* required element of type xsd:int */
	int pageSize;	/* required element of type xsd:int */
	int prizeID;	/* required element of type xsd:int */
	int rounds;	/* required element of type xsd:int */
	time_t dtBegin;	/* required element of type xsd:dateTime */
	time_t dtEnd;	/* required element of type xsd:dateTime */
	char *username;	/* optional element of type xsd:string */
	char *credential;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 34; } /* = unique id SOAP_TYPE__ns1__GetLotteryWinningList */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetLotteryWinningList() { _ns1__GetLotteryWinningList::soap_default(NULL); }
	virtual ~_ns1__GetLotteryWinningList() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetLotteryWinningListResponse_GetLotteryWinningListResult
#define SOAP_TYPE__ns1__GetLotteryWinningListResponse_GetLotteryWinningListResult (51)
/* ns1:GetLotteryWinningListResponse-GetLotteryWinningListResult */
class SOAP_CMAC _ns1__GetLotteryWinningListResponse_GetLotteryWinningListResult
{
public:
	int __size;	/* sequence of elements <-any> */
	char *__any;
	char *__any_;
public:
	virtual int soap_type() const { return 51; } /* = unique id SOAP_TYPE__ns1__GetLotteryWinningListResponse_GetLotteryWinningListResult */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetLotteryWinningListResponse_GetLotteryWinningListResult() { _ns1__GetLotteryWinningListResponse_GetLotteryWinningListResult::soap_default(NULL); }
	virtual ~_ns1__GetLotteryWinningListResponse_GetLotteryWinningListResult() { }
};
#endif

#ifndef SOAP_TYPE__ns1__GetLotteryWinningListResponse
#define SOAP_TYPE__ns1__GetLotteryWinningListResponse (35)
/* ns1:GetLotteryWinningListResponse */
class SOAP_CMAC _ns1__GetLotteryWinningListResponse
{
public:
	_ns1__GetLotteryWinningListResponse_GetLotteryWinningListResult *GetLotteryWinningListResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:GetLotteryWinningListResponse-GetLotteryWinningListResult */
	int recordCount;	/* required element of type xsd:int */
	char *msg;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 35; } /* = unique id SOAP_TYPE__ns1__GetLotteryWinningListResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__GetLotteryWinningListResponse() { _ns1__GetLotteryWinningListResponse::soap_default(NULL); }
	virtual ~_ns1__GetLotteryWinningListResponse() { }
};
#endif

#ifndef SOAP_TYPE___ns1__GetItemByCode
#define SOAP_TYPE___ns1__GetItemByCode (56)
/* Operation wrapper: */
struct __ns1__GetItemByCode
{
public:
	_ns1__GetItemByCode *ns1__GetItemByCode;	/* optional element of type ns1:GetItemByCode */
public:
	int soap_type() const { return 56; } /* = unique id SOAP_TYPE___ns1__GetItemByCode */
};
#endif

#ifndef SOAP_TYPE___ns1__GetItemByItemID
#define SOAP_TYPE___ns1__GetItemByItemID (60)
/* Operation wrapper: */
struct __ns1__GetItemByItemID
{
public:
	_ns1__GetItemByItemID *ns1__GetItemByItemID;	/* optional element of type ns1:GetItemByItemID */
public:
	int soap_type() const { return 60; } /* = unique id SOAP_TYPE___ns1__GetItemByItemID */
};
#endif

#ifndef SOAP_TYPE___ns1__GetItemValue
#define SOAP_TYPE___ns1__GetItemValue (64)
/* Operation wrapper: */
struct __ns1__GetItemValue
{
public:
	_ns1__GetItemValue *ns1__GetItemValue;	/* optional element of type ns1:GetItemValue */
public:
	int soap_type() const { return 64; } /* = unique id SOAP_TYPE___ns1__GetItemValue */
};
#endif

#ifndef SOAP_TYPE___ns1__GetClothingID
#define SOAP_TYPE___ns1__GetClothingID (68)
/* Operation wrapper: */
struct __ns1__GetClothingID
{
public:
	_ns1__GetClothingID *ns1__GetClothingID;	/* optional element of type ns1:GetClothingID */
public:
	int soap_type() const { return 68; } /* = unique id SOAP_TYPE___ns1__GetClothingID */
};
#endif

#ifndef SOAP_TYPE___ns1__AwardItem
#define SOAP_TYPE___ns1__AwardItem (72)
/* Operation wrapper: */
struct __ns1__AwardItem
{
public:
	_ns1__AwardItem *ns1__AwardItem;	/* optional element of type ns1:AwardItem */
public:
	int soap_type() const { return 72; } /* = unique id SOAP_TYPE___ns1__AwardItem */
};
#endif

#ifndef SOAP_TYPE___ns1__GetAwardItem
#define SOAP_TYPE___ns1__GetAwardItem (76)
/* Operation wrapper: */
struct __ns1__GetAwardItem
{
public:
	_ns1__GetAwardItem *ns1__GetAwardItem;	/* optional element of type ns1:GetAwardItem */
public:
	int soap_type() const { return 76; } /* = unique id SOAP_TYPE___ns1__GetAwardItem */
};
#endif

#ifndef SOAP_TYPE___ns1__GetAwardInfo
#define SOAP_TYPE___ns1__GetAwardInfo (80)
/* Operation wrapper: */
struct __ns1__GetAwardInfo
{
public:
	_ns1__GetAwardInfo *ns1__GetAwardInfo;	/* optional element of type ns1:GetAwardInfo */
public:
	int soap_type() const { return 80; } /* = unique id SOAP_TYPE___ns1__GetAwardInfo */
};
#endif

#ifndef SOAP_TYPE___ns1__Lottery
#define SOAP_TYPE___ns1__Lottery (84)
/* Operation wrapper: */
struct __ns1__Lottery
{
public:
	_ns1__Lottery *ns1__Lottery;	/* optional element of type ns1:Lottery */
public:
	int soap_type() const { return 84; } /* = unique id SOAP_TYPE___ns1__Lottery */
};
#endif

#ifndef SOAP_TYPE___ns1__GetLotteryPrize
#define SOAP_TYPE___ns1__GetLotteryPrize (88)
/* Operation wrapper: */
struct __ns1__GetLotteryPrize
{
public:
	_ns1__GetLotteryPrize *ns1__GetLotteryPrize;	/* optional element of type ns1:GetLotteryPrize */
public:
	int soap_type() const { return 88; } /* = unique id SOAP_TYPE___ns1__GetLotteryPrize */
};
#endif

#ifndef SOAP_TYPE___ns1__GetLotteryWinningTop
#define SOAP_TYPE___ns1__GetLotteryWinningTop (92)
/* Operation wrapper: */
struct __ns1__GetLotteryWinningTop
{
public:
	_ns1__GetLotteryWinningTop *ns1__GetLotteryWinningTop;	/* optional element of type ns1:GetLotteryWinningTop */
public:
	int soap_type() const { return 92; } /* = unique id SOAP_TYPE___ns1__GetLotteryWinningTop */
};
#endif

#ifndef SOAP_TYPE___ns1__GetLotteryWinningList
#define SOAP_TYPE___ns1__GetLotteryWinningList (96)
/* Operation wrapper: */
struct __ns1__GetLotteryWinningList
{
public:
	_ns1__GetLotteryWinningList *ns1__GetLotteryWinningList;	/* optional element of type ns1:GetLotteryWinningList */
public:
	int soap_type() const { return 96; } /* = unique id SOAP_TYPE___ns1__GetLotteryWinningList */
};
#endif

#ifndef SOAP_TYPE___ns1__GetItemByCode_
#define SOAP_TYPE___ns1__GetItemByCode_ (98)
/* Operation wrapper: */
struct __ns1__GetItemByCode_
{
public:
	_ns1__GetItemByCode *ns1__GetItemByCode;	/* optional element of type ns1:GetItemByCode */
public:
	int soap_type() const { return 98; } /* = unique id SOAP_TYPE___ns1__GetItemByCode_ */
};
#endif

#ifndef SOAP_TYPE___ns1__GetItemByItemID_
#define SOAP_TYPE___ns1__GetItemByItemID_ (100)
/* Operation wrapper: */
struct __ns1__GetItemByItemID_
{
public:
	_ns1__GetItemByItemID *ns1__GetItemByItemID;	/* optional element of type ns1:GetItemByItemID */
public:
	int soap_type() const { return 100; } /* = unique id SOAP_TYPE___ns1__GetItemByItemID_ */
};
#endif

#ifndef SOAP_TYPE___ns1__GetItemValue_
#define SOAP_TYPE___ns1__GetItemValue_ (102)
/* Operation wrapper: */
struct __ns1__GetItemValue_
{
public:
	_ns1__GetItemValue *ns1__GetItemValue;	/* optional element of type ns1:GetItemValue */
public:
	int soap_type() const { return 102; } /* = unique id SOAP_TYPE___ns1__GetItemValue_ */
};
#endif

#ifndef SOAP_TYPE___ns1__GetClothingID_
#define SOAP_TYPE___ns1__GetClothingID_ (104)
/* Operation wrapper: */
struct __ns1__GetClothingID_
{
public:
	_ns1__GetClothingID *ns1__GetClothingID;	/* optional element of type ns1:GetClothingID */
public:
	int soap_type() const { return 104; } /* = unique id SOAP_TYPE___ns1__GetClothingID_ */
};
#endif

#ifndef SOAP_TYPE___ns1__AwardItem_
#define SOAP_TYPE___ns1__AwardItem_ (106)
/* Operation wrapper: */
struct __ns1__AwardItem_
{
public:
	_ns1__AwardItem *ns1__AwardItem;	/* optional element of type ns1:AwardItem */
public:
	int soap_type() const { return 106; } /* = unique id SOAP_TYPE___ns1__AwardItem_ */
};
#endif

#ifndef SOAP_TYPE___ns1__GetAwardItem_
#define SOAP_TYPE___ns1__GetAwardItem_ (108)
/* Operation wrapper: */
struct __ns1__GetAwardItem_
{
public:
	_ns1__GetAwardItem *ns1__GetAwardItem;	/* optional element of type ns1:GetAwardItem */
public:
	int soap_type() const { return 108; } /* = unique id SOAP_TYPE___ns1__GetAwardItem_ */
};
#endif

#ifndef SOAP_TYPE___ns1__GetAwardInfo_
#define SOAP_TYPE___ns1__GetAwardInfo_ (110)
/* Operation wrapper: */
struct __ns1__GetAwardInfo_
{
public:
	_ns1__GetAwardInfo *ns1__GetAwardInfo;	/* optional element of type ns1:GetAwardInfo */
public:
	int soap_type() const { return 110; } /* = unique id SOAP_TYPE___ns1__GetAwardInfo_ */
};
#endif

#ifndef SOAP_TYPE___ns1__Lottery_
#define SOAP_TYPE___ns1__Lottery_ (112)
/* Operation wrapper: */
struct __ns1__Lottery_
{
public:
	_ns1__Lottery *ns1__Lottery;	/* optional element of type ns1:Lottery */
public:
	int soap_type() const { return 112; } /* = unique id SOAP_TYPE___ns1__Lottery_ */
};
#endif

#ifndef SOAP_TYPE___ns1__GetLotteryPrize_
#define SOAP_TYPE___ns1__GetLotteryPrize_ (114)
/* Operation wrapper: */
struct __ns1__GetLotteryPrize_
{
public:
	_ns1__GetLotteryPrize *ns1__GetLotteryPrize;	/* optional element of type ns1:GetLotteryPrize */
public:
	int soap_type() const { return 114; } /* = unique id SOAP_TYPE___ns1__GetLotteryPrize_ */
};
#endif

#ifndef SOAP_TYPE___ns1__GetLotteryWinningTop_
#define SOAP_TYPE___ns1__GetLotteryWinningTop_ (116)
/* Operation wrapper: */
struct __ns1__GetLotteryWinningTop_
{
public:
	_ns1__GetLotteryWinningTop *ns1__GetLotteryWinningTop;	/* optional element of type ns1:GetLotteryWinningTop */
public:
	int soap_type() const { return 116; } /* = unique id SOAP_TYPE___ns1__GetLotteryWinningTop_ */
};
#endif

#ifndef SOAP_TYPE___ns1__GetLotteryWinningList_
#define SOAP_TYPE___ns1__GetLotteryWinningList_ (118)
/* Operation wrapper: */
struct __ns1__GetLotteryWinningList_
{
public:
	_ns1__GetLotteryWinningList *ns1__GetLotteryWinningList;	/* optional element of type ns1:GetLotteryWinningList */
public:
	int soap_type() const { return 118; } /* = unique id SOAP_TYPE___ns1__GetLotteryWinningList_ */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (119)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 119; } /* = unique id SOAP_TYPE_SOAP_ENV__Header */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (120)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 120; } /* = unique id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (122)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 122; } /* = unique id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (125)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 125; } /* = unique id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (126)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 126; } /* = unique id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (7)
typedef char *xsd__decimal;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemByCode(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemByCode *ns1__GetItemByCode, _ns1__GetItemByCodeResponse *ns1__GetItemByCodeResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemByItemID(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemByItemID *ns1__GetItemByItemID, _ns1__GetItemByItemIDResponse *ns1__GetItemByItemIDResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemValue(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemValue *ns1__GetItemValue, _ns1__GetItemValueResponse *ns1__GetItemValueResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetClothingID(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetClothingID *ns1__GetClothingID, _ns1__GetClothingIDResponse *ns1__GetClothingIDResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__AwardItem(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__AwardItem *ns1__AwardItem, _ns1__AwardItemResponse *ns1__AwardItemResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAwardItem(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAwardItem *ns1__GetAwardItem, _ns1__GetAwardItemResponse *ns1__GetAwardItemResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAwardInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAwardInfo *ns1__GetAwardInfo, _ns1__GetAwardInfoResponse *ns1__GetAwardInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Lottery(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__Lottery *ns1__Lottery, _ns1__LotteryResponse *ns1__LotteryResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryPrize(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryPrize *ns1__GetLotteryPrize, _ns1__GetLotteryPrizeResponse *ns1__GetLotteryPrizeResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryWinningTop(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryWinningTop *ns1__GetLotteryWinningTop, _ns1__GetLotteryWinningTopResponse *ns1__GetLotteryWinningTopResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryWinningList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryWinningList *ns1__GetLotteryWinningList, _ns1__GetLotteryWinningListResponse *ns1__GetLotteryWinningListResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemByCode_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemByCode *ns1__GetItemByCode, _ns1__GetItemByCodeResponse *ns1__GetItemByCodeResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemByItemID_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemByItemID *ns1__GetItemByItemID, _ns1__GetItemByItemIDResponse *ns1__GetItemByItemIDResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetItemValue_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetItemValue *ns1__GetItemValue, _ns1__GetItemValueResponse *ns1__GetItemValueResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetClothingID_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetClothingID *ns1__GetClothingID, _ns1__GetClothingIDResponse *ns1__GetClothingIDResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__AwardItem_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__AwardItem *ns1__AwardItem, _ns1__AwardItemResponse *ns1__AwardItemResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAwardItem_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAwardItem *ns1__GetAwardItem, _ns1__GetAwardItemResponse *ns1__GetAwardItemResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAwardInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetAwardInfo *ns1__GetAwardInfo, _ns1__GetAwardInfoResponse *ns1__GetAwardInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Lottery_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__Lottery *ns1__Lottery, _ns1__LotteryResponse *ns1__LotteryResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryPrize_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryPrize *ns1__GetLotteryPrize, _ns1__GetLotteryPrizeResponse *ns1__GetLotteryPrizeResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryWinningTop_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryWinningTop *ns1__GetLotteryWinningTop, _ns1__GetLotteryWinningTopResponse *ns1__GetLotteryWinningTopResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLotteryWinningList_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetLotteryWinningList *ns1__GetLotteryWinningList, _ns1__GetLotteryWinningListResponse *ns1__GetLotteryWinningListResponse);

#endif

/* End of soapStub.h */
